# Generated by Django 2.1.2 on 2018-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
    ]
