# Generated by Django 2.1.2 on 2018-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_link',
            field=models.CharField(default='y9ZbtAvv9CJ0oJ8bfHtpdL8hXbI', max_length=27),
            preserve_default=False,
        ),
    ]
