# Generated by Django 2.1.2 on 2018-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite_invite_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='id',
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_link',
            field=models.CharField(max_length=27, primary_key=True, serialize=False),
        ),
    ]
