# Generated by Django 2.1.2 on 2018-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181105_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='activated_link',
            field=models.BooleanField(default=False),
        ),
    ]
