# Generated by Django 2.1.1 on 2018-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flockstream', '0002_auto_20180927_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='published_by',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
